# Usa una imagen base de Node.js
FROM node:18-alpine

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el código fuente
COPY . .

# Exponer el puerto para el servidor
EXPOSE 3000

# Comando por defecto para ejecutar la aplicación
CMD ["npm", "start"]
