apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment-green
  namespace: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-green
  template:
    metadata:
      labels:
        app: backend-green
    spec:
      containers:
        - name: backend
          image: ghcr.io/billybala/multienv-app-kubernetes/backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: NODE_ENV
              value: production
            - name: MONGO_URI
              value: mongodb://mongodb-service.database.svc.cluster.local:27017/mydb
            - name: REDIS_HOST
              value: redis-service.cache.svc.cluster.local
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
