apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: frontend
  labels:
    app: frontend
data:
  nginx.conf: |
    events {
        worker_connections  1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        server {
            listen 80;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                try_files $uri /index.html;
            }

            location /shared/ {
                alias /usr/share/nginx/html/shared/;
                autoindex on;
            }

            location /api/ {
                proxy_pass http://backend-service.backend.svc.cluster.local:8000/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
