apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
  labels:
    app: frontend
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: shared-storage
  hostPath:
    path: "/usr/share/nginx/html/shared"
    type: DirectoryOrCreate
