apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail-daemonset
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: default
      containers:
        - name: promtail
          image: grafana/promtail:latest
          imagePullPolicy: IfNotPresent
          args:
            - "-config.file=/etc/promtail/promtail-config.yml"
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail/promtail-config.yml
            - name: varlog
              mountPath: /var/log
              readOnly: true
      volumes:
        - name: promtail-config
          configMap:
            name: promtail-config
            items:
              - key: promtail-config.yml
                path: promtail-config.yml
        - name: varlog
          hostPath:
            path: /var/log
