global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager-service:9093"] # Agrega la configuración de Alertmanager

rule_files:
  - "/etc/prometheus/rules/*.rules.yaml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # Agrega una configuración para la monitorización de contenedores Docker
  - job_name: "kubernetes-logs"
    static_configs:
      - targets: ["loki-service:3100"]
        labels:
          job: "docker-logs"
